include: package:flutter_lints/flutter.yaml

analyzer:
  # Exclui arquivos gerados automaticamente e infraestrutura genérica
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/backend/row.dart"
    - "lib/backend/table.dart"
    - "lib/core/nav/nav.dart"

  # Melhora a análise de tipos (torna o Dart mais rigoroso)
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # --- PERFORMANCE ---
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true

    # --- SEGURANÇA ASYNC (Crucial para seu trabalho com Supabase) ---
    # Evita crashes ao usar o Context após um 'await'
    use_build_context_synchronously: true
    unawaited_futures: true
    avoid_slow_async_io: true

    # --- ESTILO E ORGANIZAÇÃO ---
    # Força você a usar aspas simples (padrão Dart)
    prefer_single_quotes: true
    # Garante que o 'child' venha por último no widget (melhora leitura)
    sort_child_properties_last: true
    # Remove prints em produção (use log ou debugPrint)
    avoid_print: true
    # Força tipagem no retorno de funções
    always_declare_return_types: true
    # Exige o uso de 'final' para variáveis que não mudam
    prefer_final_locals: true
    prefer_final_fields: true

    # --- EVITAR ERROS COMUNS ---
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    empty_statements: true
    no_logic_in_create_state: true
